# ref: https://mise.jdx.dev/configuration.html
#:schema https://mise.jdx.dev/schema/mise.json

min_version = "2026.7.5"

[tools]
hk = "1.51.0"
pkl = "0.32.0"
actionlint = "1.7.12"
ghalint = "1.5.6"
pinact = "4.1.0"
zizmor = "1.27.0"
shellcheck = "0.11.0"
lychee = "0.24.2"
"npm:semantic-release" = "25.0.6"

[task_config]
includes = ["tasks.toml"]

[hooks]
postinstall = """
{% if env.CI is undefined %}
  hk install --mise
{% endif %}
"""
