# ref: https://mise.jdx.dev/tasks/
#:schema https://mise.jdx.dev/schema/mise-task.json

[check]
usage = '''
flag "--lint" help="Run hk check instead of fix"
flag "--flaky" help="Also enable hk flaky profile (lychee)"
'''
run = """
hk \
  {% if usage.flaky %}--profile flaky {% endif %}\
  {% if usage.lint %}check{% else %}fix{% endif %} \
  --all --no-progress --no-fail-fast
"""
description = "Run hk linters and formatters."
